### ISSUE TITLE
WindowManager.java not up to date

### ISSUE THREAD

**Issue by Archonic944** [KernelGhost/BrainwaveDetectionUtility#1]
Specifically, these two classes are missing:

* frmVideoGames
* frmSerialOut

<img width="458" alt="image" src="https://github.com/KernelGhost/BrainwaveDetectionUtility/assets/55026152/20fb3b9b-dd8e-40f8-a19f-5bdefabf344c">

**Comment by KernelGhost** [comment]
Thank you for your interest in this project! Unfortunately, I am unable to reproduce this issue. After cloning the repository, I was able to open, run and compile the project within [Eclipse](https://eclipseide.org/). The classes do not appear to be missing on my end, and Eclipse does not report any warnings or issues.

Could you please provide more details on the issue? What IDE are you using to open the project? Are the missing class files physically present within `/BrainwaveDetectionUtility/src`? Does the same issue occur on other computers as well?

Looking forward to hearing from you 😊

**Comment by Archonic944** [comment]
Unfortunately, it doesn't work by default when opened in IntelliJ:
![image](https://github.com/KernelGhost/BrainwaveDetectionUtility/assets/55026152/3bcb16ae-48f6-4fe5-99df-0b9990213166)
You can see that the files are highlighted in yellow which means that IntelliJ thinks they aren't part of the project. Usually IntelliJ handles eclipse files fine... not sure what's wrong.

**Comment by KernelGhost** [comment]
I was able to get the project running in IntelliJ IDEA 2022.2.2 (Edu). Are you correctly specifying a launch configuration and specifying the required libraries?

Make sure you:
1. Add [`jSerialComm`](https://github.com/Fazecast/jSerialComm) and [`XChart`](https://knowm.org/open-source/xchart/) as libraries via 'File > Project Structure > Project Settings > Libraries'.
2. Add a new 'Application' launch configuration pointing to Main.java.

<img width="960" alt="BDU in IntelliJ" src="https://github.com/KernelGhost/BrainwaveDetectionUtility/assets/57999059/1b11519a-fe99-46b5-9294-ef323e924ec0">

Let me know how you go! 😊

**Comment by Archonic944** [comment]
Got it. I probably don't need to modify it anyway, I'm just going to use the JAR. I'm about to open another issue about something else, though.
